name: agrisensor_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  mlkit: ^0.15.0
  firebase_ml_vision: ^0.9.3+3
  image: ^2.1.8
  image_picker: ^0.6.1+11
  tflite: ^0.0.5
  carousel_slider: ^1.3.1
  flutter_svg: ^0.15.0
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.7
  firebase_storage: ^3.0.6
  firebase_core: ^0.4.0+9
  shared_preferences: ^0.5.3+4
  file_picker: ^1.4.3+1
  dio: ^3.0.7
  path: ^1.6.4
  pdf_render: ^0.57.1
  intl: ^0.16.0

#dev_dependencies:
  #flutter_test:
    #sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/testImage1.jpg
    - assets/plant_disease_model.tflite
    - assets/plant_disease_model1.tflite
    - assets/plant_labels.txt
    - assets/runtestIcon.png
    - assets/SVGPics/apple.svg
    - assets/SVGPics/blueberry.svg
    - assets/SVGPics/cherry.svg
    - assets/SVGPics/corn.svg
    - assets/SVGPics/grapes.svg
    - assets/SVGPics/orange.svg
    - assets/SVGPics/peppersbell.svg
    - assets/SVGPics/potato.svg
    - assets/SVGPics/raspberry.svg
    - assets/SVGPics/soybean.svg
    - assets/SVGPics/squashpowdery.svg
    - assets/SVGPics/strawberry.svg
    - assets/SVGPics/tomato.svg
    - assets/SVGPics/peach.svg
    - assets/SVGPics/home.svg
    - assets/SVGPics/profile.svg
    - assets/SVGPics/facebook.svg
    - assets/SVGPics/google.svg
    - assets/SVGPics/profileImage.svg
    - assets/SVGPics/brokenImageIcon.svg
    - assets/SVGPics/pickFromGallery.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa/Comfortaa-Light.ttf
        - asset: assets/fonts/Comfortaa/Comfortaa-Medium.ttf
        - asset: assets/fonts/Comfortaa/Comfortaa-Bold.ttf
        - asset: assets/fonts/Comfortaa/Comfortaa-SemiBold.ttf
    - family: KaushanScript
      fonts:
        - asset: assets/fonts/KaushanScript-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
